export const FAVOURITE_SHOW = "FAVOURITE_SHOW ";
export const FAVOURITE_PEOPLE = "FAVOURITE_PEOPLE";
export const SET_FAVOURITE_SHOW = "SET_FAVOURITE_SHOW";
export const SET_FAVOURITE_PEOPLE = "SET_FAVOURITE_PEOPLE";

